fullnameOverride: argocd
global:
  domain: argocd.localhost
crds:
  keep: false
configs:
  params:
    server.insecure: true
  repositories:
    - name: myk8s
      type: git
      url: https://github.com/bulmust/myk8s
      path:
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 3Gi
dex:
  enabled: false
redis:
  exporter:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 300Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 2Gi
server:
  extensions:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 2Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - argocd.localhost
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.localhost
repoServer:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 4Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  rbac:
    - verbs:
        - get
        - list
        - watch
      apiGroups:
        - ''
      resources:
        - secrets
        - configmaps
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 2Gi
notifications:
  argocdUrl: argocd.localhost
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 1Gi
