# resources:
#   limits:
#     memory: 600Mi
#   requests:
#     cpu: 120m
#     memory: 250Mi
# serviceMonitor:
#   enabled: true
config:
  clients:
    - url: http://loki-distributed-gateway/loki/api/v1/push
      tenant_id: myk8s
      external_labels:
        cluster: myk8s
      tls_config:
        insecure_skip_verify: true
# tolerations:
#   - key: "product"
#     operator: "Equal"
#     value: "monitoring"
#     effect: "NoSchedule"
#   - key: "product"
#     operator: "Equal"
#     value: "apps"
#     effect: "NoSchedule"
#   - key: node-role.kubernetes.io/control-plane
#     operator: Exists
#     effect: NoSchedule
