{
 "title": "Node - Resources",
 "tags": [ "Home" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"apiserver\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Summary -  $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Weeks" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((time() - node_boot_time_seconds{cluster=\"$cluster\"})/60/60/24/7) * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count by(instance) (node_cpu_seconds_total{cluster=\"$cluster\", mode=\"system\"})) * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory (RAM)",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"})) * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU - $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[1m]) * 100) * on(instance) group_left(nodename) (node_uname_info{cluster=\"$cluster\"}))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU (Last)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[1m]) * 100) * on(instance) group_left(nodename) (node_uname_info{cluster=\"$cluster\"}))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory (Avareged 1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{cluster=\"$cluster\"}[1m]) + avg_over_time(node_memory_Cached_bytes{cluster=\"$cluster\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{cluster=\"$cluster\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{cluster=\"$cluster\"}[1m])))) * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory (Last)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{cluster=\"$cluster\"}[15s]) + avg_over_time(node_memory_Cached_bytes{cluster=\"$cluster\"}[15s]) + avg_over_time(node_memory_Buffers_bytes{cluster=\"$cluster\"}[15s])) / avg_over_time(node_memory_MemTotal_bytes{cluster=\"$cluster\"}[15s])))) * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  }
 ]
}