ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.localhost
  path: /
  pathType: "ImplementationSpecific"
  tls:
    - secretName: grafana-localhost-tls
      hosts:
        - grafana.localhost
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 140m
    memory: 250Mi
persistence:
  type: pvc
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
adminUser: admin
adminPassword: admin